#!/usr/bin/env ruby

VERSION="0.0.0"
REVISION="1"

if ARGV.length > 1
  raise "Too much command line arguments."
end

# Argument handling
require_relative 'argument'

arg=Argument.new

help = ArgumentOption.new('--help', 'Show usage text and exit') do
  puts "irbs v#{VERSION}-#{REVISION} usage text :\n"
  puts "An Inspection/Representation Based web Server."
  
  puts "\nOptions :"
  puts "  --help, -h, -?   Print this usage text and exit with 0 exit status."
  arg.opts.each do a
    puts "  #{a}"
  end
  exit(0)
end
help.add_alias "-h"
help.add_alias "-?"
arg.add(help)
arg.consume(ARGV)

# Content/input directory
dir = ARGV[0]
if dir.nil?
  dir = Dir.pwd
else
  dir = File.expand_path(dir)
end

unless File.directory? dir
  raise "Directory passed as first argument must exist"
end  

