#!/usr/bin/env ruby

VERSION="0.0.1"
REVISION=13

# Check if we are running from the bundler environment. If you call this script
# directly (without bundler), you may have require error (especially with the
# 'mime-types' gem). As this require error can occur from any ''require'
# statement, it must be placed before any.
if not defined?(Bundler) then
  raise "This script shoudn't be ran directly. Please run it via Bundler!"
end

# Argument handling
require_relative 'argument'
require_relative 'server'

srv = Server.new

arg=Argument.new
puts ARGV

ni = ArgumentOption.new('--non-interactive',
                          'Print endpoint to console and exit.') do
  srv.interactive = false
end
ni.add_alias "-n"
arg.add ni

ep = ArgumentOption.new('--endpoint',
                          'The endpoint to print in non-interactive mode.') do
  srv.endpoint = ARGV[ARGV.index('--endpoint') + 1]
  exit(0)
end
ep.add_alias "-e"
arg.add ep

po = ArgumentOption.new('--port',
                          'The port to listen client from.') do
  srv.port = ARGV[ARGV.index('--port') + 1]
  exit(0)
end
po.add_alias "-p"
arg.add po

arg.add_usage
arg.consume(ARGV)

# Content/input directory
p ARGV
dirs = arg.only_dirs(ARGV)
p dirs
dir = dirs[0]
if dir.nil?
  dir = Dir.pwd
else
  dir = File.expand_path(dir)
end

unless File.directory? dir
  raise "Directory passed as first argument (#{dir}) doesn't exist"
end  

srv.run dir
